export enum DocumentStandardTarget {
  ECOWAS_ID_CARD = "ECOWAS_ID_CARD",
  EU_ID_CARD = "EU_ID_CARD",
  EU_PASSPORT = "EU_PASSPORT",
  EU_RESIDENT_PERMIT = "EU_RESIDENT_PERMIT",
  ICAO_DOC_9303 = "ICAO_DOC_9303",
}
